name: Trigger Production Deploy
on:
  push:
    tags:
      - '*'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger production deploy
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MIRROR_REPO_TOKEN }}" \
          https://api.github.com/repos/matt-secondlane/secondlane-tma-mirror/dispatches \
          -d '{"event_type": "production_deploy", "client_payload": {"tag": "${{ github.ref_name }}"}}'